import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Web3 from 'web3'


export default function Home() {
  // Methods
  /**
   * Login on Metamask
   */
  async function loginMetamask(e) {
    // e.preventDefault();
    return new Promise((resolve, reject) => {
      if (typeof window.ethereum !== 'undefined') {
        const web3 = new Web3(window.ethereum)
        try {
          window.ethereum.request({method: "eth_requestAccounts"})
          resolve(web3)
        } catch (error) {
          reject(error)
        }
      }
    })
  }
  // Render
  return (
    <div className={styles.container}>
      <Head>
        <title>Soldity Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h5 className={styles.h4}>
          Gestionar tareas con Soldity
        </h5>
        <div>
          <button onClick={loginMetamask}>Connect wallet</button>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
